In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',500)
import warnings
warnings.filterwarnings("ignore")
#pd.set_option('display.max_columns',None)

In [4]:
dataset=pd.read_csv(r'D:\Bondora_raw.csv',low_memory=False)
dataset
#dataset=pd.read_excel(r"D:\mockd.xlsx")

,ReportAsOfEOD,LoanId,LoanNumber,ListedOnUTC,BiddingStartedOn,BidsPortfolioManager,BidsApi,BidsManual,UserName,NewCreditCustomer,LoanApplicationStartedDate,LoanDate,ContractEndDate,FirstPaymentDate,MaturityDate_Original,MaturityDate_Last,ApplicationSignedHour,ApplicationSignedWeekday,VerificationType,LanguageCode,Age,DateOfBirth,Gender,Country,AppliedAmount,Amount,Interest,LoanDuration,MonthlyPayment,County,City,UseOfLoan,Education,MaritalStatus,NrOfDependants,EmploymentStatus,EmploymentDurationCurrentEmployer,EmploymentPosition,WorkExperience,OccupationArea,HomeOwnershipType,IncomeFromPrincipalEmployer,IncomeFromPension,IncomeFromFamilyAllowance,IncomeFromSocialWelfare,IncomeFromLeavePay,IncomeFromChildSupport,IncomeOther,IncomeTotal,ExistingLiabilities,LiabilitiesTotal,RefinanceLiabilities,DebtToIncome,FreeCash,MonthlyPaymentDay,ActiveScheduleFirstPaymentReached,PlannedPrincipalTillDate,PlannedInterestTillDate,LastPaymentOn,CurrentDebtDaysPrimary,DebtOccuredOn,CurrentDebtDaysSecondary,DebtOccuredOnForSecondary,ExpectedLoss,LossGivenDefault,ExpectedReturn,ProbabilityOfDefault,DefaultDate,PrincipalOverdueBySchedule,PlannedPrincipalPostDefault,PlannedInterestPostDefault,EAD1,EAD2,PrincipalRecovery,InterestRecovery,RecoveryStage,StageActiveSince,ModelVersion,Rating,EL_V0,Rating_V0,EL_V1,Rating_V1,Rating_V2,Status,Restructured,ActiveLateCategory,WorseLateCategory,CreditScoreEsMicroL,CreditScoreEsEquifaxRisk,CreditScoreFiAsiakasTietoRiskGrade,CreditScoreEeMini,PrincipalPaymentsMade,InterestAndPenaltyPaymentsMade,PrincipalWriteOffs,InterestAndPenaltyWriteOffs,PrincipalBalance,InterestAndPenaltyBalance,NoOfPreviousLoansBeforeLoan,AmountOfPreviousLoansBeforeLoan,PreviousRepaymentsBeforeLoan,PreviousEarlyRepaymentsBefoleLoan,PreviousEarlyRepaymentsCountBeforeLoan,GracePeriodStart,GracePeriodEnd,NextPaymentDate,NextPaymentNr,NrOfScheduledPayments,ReScheduledOn,PrincipalDebtServicingCost,InterestAndPenaltyDebtServicingCost,ActiveLateLastPaymentCategory
0,2020-01-27,F0660C80-83F3-4A97-8DA0-9C250112D6EC,659,2009-06-11 16:40:39,2009-06-11 16:40:39,0,0,115.0410,KARU,True,2009-06-11 16:40:39,2009-06-16,2010-07-06,2009-07-27,2010-06-25,2010-06-25,17,5,2.0,1,61,1947-11-26,1.0,EE,319.5582,115.0408,30.00,12,NaN,HARJU,TALLINN,7,3.0,1.0,0,3.0,UpTo3Years,klienditeenindaja,MoreThan25Years,7.0,NaN,6000.0,0.0,0.0,0.0,0.0,0.0,4500.0,10500.0,0,0.00,0,0.00,0.00,25,True,1800.0000,319.0800,2010-07-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Repaid,False,NaN,91-120,NaN,NaN,NaN,NaN,115.0408,20.4222,0.00,0.00,0.00,0.00,1,83.0852,0.0000,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,NaN
1,2020-01-27,978BB85B-1C69-4D51-8447-9C240104A3A2,654,2009-06-10 15:48:57,2009-06-10 15:48:57,0,0,140.6057,koort681,False,2009-06-10 15:48:57,2009-06-15,2009-07-07,2009-07-15,2009-07-15,2009-07-15,20,4,2.0,1,48,1960-11-05,1.0,EE,191.7349,140.6057,25.00,1,NaN,IDA-VIRU,KOHTLA-JARVE,7,5.0,4.0,0,3.0,MoreThan5Years,Õppealajuhataja lasteaias,MoreThan25Years,16.0,NaN,8300.0,0.0,0.0,0.0,0.0,0.0,2500.0,10800.0,0,0.00,0,0.00,0.00,15,True,2200.0000,45.8300,2009-07-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Repaid,False,NaN,NaN,NaN,NaN,NaN,NaN,140.6057,2.0227,0.00,0.00,0.00,0.00,2,255.6467,258.6256,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,NaN
2,2020-01-27,EA44027E-7FA7-4BB2-846D-9C1F013C8A22,641,2009-06-05 19:12:29,2009-06-05 19:12:29,0,0,319.5580,0ie,True,2009-06-05 19:12:29,2009-06-15,NaN,2009-07-27,2011-02-25,2014-05-13,20,6,2.0,1,58,1950-11-13,1.0,EE,319.5582,319.5409,25.00,20,NaN,PÄRNU,PÄRNU,2,4.0,1.0,0,3.0,UpTo4Years,teenindaja,MoreThan25Years,9.0,NaN,5000.0,0.0,0.0,0.0,0.0,0.0,2000.0,7000.0,0,0.00,0,0.00,0.00,25,True,319.5409,197.2926,2012-10-01,2813.0,2012-05-14,2935.0,2012-01-13,NaN,NaN,NaN,NaN,2012-07-16,116.35,236.97,38.24,279.5049,270.7323,163.1549,50.99,NaN,2016-03-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Late,True,180+,180+,NaN,NaN,NaN,NaN,203.1909,59.7626,0.00,0.00,116.35,414.07,0,0.0000,0.0000,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,180+
3,2020-01-27,CE67AD25-2951-4BEE-96BD-9C2700C61EF4,668,2009-06-13 12:01:20,2009-06-13 12:01:20,0,0,57.5205,Alyona,True,2009-06-13 12:01:20,2009-06-15,2010-09-15,2009-07-15,2010-09-15,2010-09-15,12,7,2.0,1,23,1986-03-29,1.0,EE,127.8233,57.5205,45.00,15,NaN,HARJU,PALDISKI,0,2.0,3.0,1,NaN,UpTo2Years,juhtmekoitja,2To5Years,1.0,NaN,11000.0,0.0,0.0,0.0,0.0,0.0,600.0,11600.0,0,0.00,0,0.00,0.00,15,True,900.0000,293.1000,2010-09-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Repaid,False,NaN,31-60,NaN,NaN,NaN,NaN,57.5205,18.7323,0.00,0.00,0.00,0.00,1,134.2144,0.0000,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,NaN
4,2020-01-27,9408BF8C-B159-4D6A-9D61-9C2400A986E3,652,2009-06-10 10:17:13,2009-06-10 10:17:13,0,0,319.5582,Kai,True,2009-06-10 10:17:13,2009-06-14,2016-07-28,2009-07-27,2010-06-25,2010-06-25,10,4,2.0,1,25,1983-09-30,1.0,EE,319.5582,319.5436,30.00,12,NaN,TARTU,TARTU,6,4.0,2.0,0,3.0,UpTo2Years,klienditeenindaja,5To10Years,7.0,NaN,6800.0,0.0,0.0,0.0,0.0,0.0,0.0,6800.0,0,0.00,0,0.00,0.00,25,True,5000.0000,833.8100,2015-07-16,NaN,NaN,3835.0,2009-07-27,NaN,NaN,NaN,NaN,2009-09-28,NaN,247.76,29.84,319.5436,319.5436,319.5436,220.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Repaid,False,NaN,180+,NaN,NaN,NaN,NaN,319.5436,220.4200,0.00,2.40,0.00,0.00,1,146.9966,0.0000,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,180+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134524,2020-01-27,A9C9EF0F-4E79-4930-BA8A-A4130077FCC2,283484,2015-01-02 16:31:36,2015-01-02 16:31:36,2515,0,485.0000,BO73K5A6A,True,2015-01-01 07:17:03,2015-01-06,2019-02-13,2015-03-02,2020-02-03,2020-02-03,16,6,3.0,4,37,1977-02-07,0.0,FI,3000.0000,3000.0000,31.01,60,107.68,PÄIJÄT-HÄME,LAHTI,0,3.0,3.0,0,3.0,MoreThan5Years,Worker,15To25Years,1.0,5.0,1400.0,0.0,0.0,0.0,0.0,0.0,0.0,1400.0,1,500.00,0,7.69,792.32,1,True,1411.6000,3000.0000,2019-02-12,1791.0,2015-03-02,1791.0,2015-03-02,0.146732,0.90,0.163368,0.125412,2015-05-04,0.00,2860.87,2779.85,3000.0000,3000.0000,2308.1900,0.00,2.0,2018-12-21 10:08:52,1.0,E,NaN,NaN,0.146732,E,HR,Repaid,False,180+,180+,NaN,NaN,RL2,NaN,2308.1900,0.0000,691.81,1552.18,0.00,0.00,0,0.0000,0.0000,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1040.06,180+
134525,2020-01-27,787345C2-7606-4F72-8FE2-A4170082D77C,285168,2015-01-05 16:14:26,2015-01-05 16:14:26,1880,0,1120.0000,BO311A49,False,2015-01-05 07:56:22,2015-01-06,2019-02-07,2015-03-05,2020-02-05,2019-02-20,16,2,3.0,4,35,1979-05-17,0.0,FI,3000.0000,3000.0000,18.25,60,85.33,POHJOIS KARJAALA,JOENSUU,2,3.0,3.0,0,3.0,MoreThan5Years,MiddleManager,15To25Years,8.0,1.0,2265.0,0.0,0.0,0.0,0.0,0.0,0.0,2265.0,5,1777.46,0,31.58,520.67,7,True,0.0000,16.3200,2019-02-07,NaN,NaN,NaN,NaN,0.053246,0.90,0.129254,0.045510,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2018-07-23 17:00:07.437000000,1.0,B,NaN,NaN,0.053246,B,E,Repaid,False,NaN,31-60,NaN,NaN,RL2,NaN,3000.0000,1990.0300,0.00,0.00,0.00,0.00,1,3000.0000,389.3600,0.0,0,2017-06-27,2018-06-20,NaN,NaN,NaN,NaN,0.0,0.00,NaN
134526,2020-01-27,E2D3384D-289A-4B4D-A2DA-A40F00F7C755,281602,2015-01-02 14:04:27,2015-01-02 14:04:27,1975,0,525.0000,BO41K639A,True,2014-12-28 15:01:47,2015-01-06,NaN,2015-03-02,2020-02-03,2020-02-03,13,6,1.0,4,40,1974-01-25,0.0,FI,2500.0000,2500.0000,24.83,60,80.42,VARSINAIS-SUOMI,SAUVO,0,3.0,1.0,1,5.0,MoreThan5Years,Owner,5To10Years,6.0,1.0,2500.0,0.0,0.0,0.0,0.0,0.0,0.0,2500.0,2,1350.00,0,3.22,1069.58,1,True,1264.4500,2428.4400,2020-01-17,1700.0,2015-06-01,1700.0,2015-06-01,0.104219,0.90,0.144081,0.089076,2015-08-04,558.68,2293.22,1582.04,2434.9900,2235.6600,1804.7500,0.00,2.0,2019-02-28 17:02:53,1.0,D,NaN,NaN,0.104219,D,HR,Late,False,180+,180+,NaN,NaN,RL2,NaN,1869.7600,199.3300,0.00,0.00,630.24,1227.98,0,0.0000,0.0000,0.0,0,NaN,NaN,NaN,0.0,60.0,NaN,0.0,1051.85,8-15
134527,2020-01-27,7CC7AB74-995B-4467-958A-A41700F78D59,285431,2015-01-05 16:56:12,2015-01-05 16:56:12,1840,0,1160.0000,BO45A925,False,2015-01-05 15:01:18,2015-01-06,2019-12-23,2015-03-02,2020-02-03,2020-08-03,16,2,4.0,1,47,1967-01-28,1.0,EE,3000.0000,3000.0000,17.74,60,84.51,VALGA,VALGA,7,5.0,1.0,1,3.0,MoreThan5Years,Worker,MoreThan25Years,17.0,4.0,521.0,0.0,19.0,0.0,0.0,0.0,0.0,540.0,8,732.05,2,44.35,50.49,1,True,888.5600,2588.2100,2019-12-20,1318.0,2016-06-17,1395.0,2016-04-01,0.035612,0.65,0.141788,0.042144,2016-06-17,167.41,2081.26,1104.98,2588.2100,2026.6800,1845.7500,0.00,2.0,2017-12-29 17:51:02,1.0,B,NaN,NaN,0.035612,B,B,Repaid,True,180+,180+,NaN,NaN,NaN,1000.0,2257.5400,561.5300,742.46,4829.92,0.00,0.00,1,500.0000,96.8000,0.0,0,2016-04-01,2016-10-03,NaN,NaN,NaN,NaN,0.0,889.50,31-60
134528,2020-01-27,3A0DEBF3-292C-4EB4-B71A-A4170157749D,285630,2015-01-06 11:07:06,2015-01-06 11:07:06,2990,0,10.0000,BO152923A,False,2015-01-05 20:50:24,2015-01-06,NaN,2015-03-03,2020-02-03,2020-08-12,11,3,4.0,1,21,1993-09-30,1.0,EE,3000.0000,3000.0000,30.50,60,106.74,HARJU,TALLINN,0,4.0,3.0,0,3.0,UpTo3Years,Worker,2To5Years,19.0,2.0,500.0,0.0,0.0,0.0,0.0,0.0,0.0,500.0,5,531.03,1,35.03,74.86,3,True,972.6900,2260.0000,2019-10-15,1488.0,2015-12-30,1595.0,2015-09-14,0.116235,0.65,0.188765,0.137556,2015-12-30,897.50,2260.00,2537.09,2888.5900,2205.3800,1362.5000,0.00,2.0,2020-01-21 11:20:06.740000000,1.0,D,NaN,NaN,0.116235,D,E,Late,True,180+,180+,NaN,NaN,NaN,1000.0,1473.9100,683.2100,0.00,0.00,1526.09,9019.04,1,2500.0000,242.6400,0.0,0,2015-09-14,2016-03-14,NaN,0.0,60.0,2015-09-09,0.0,604.80,91-120

In [5]:
dataset.columns
dataset.shape

(134529, 112)

In [6]:
pd.set_option("display.max_rows", None ,"display.max_columns",None)
dataset.isna().sum()
dataset['Status'].value_counts()

Current    57135
Late       45772
Repaid     31622
Name: Status, dtype: int64

In [7]:
dataset.head()
miss=['ContractEndDate', 'NrOfDependants', 'EmploymentPosition',
       'WorkExperience', 'PlannedPrincipalTillDate', 'CurrentDebtDaysPrimary',
       'DebtOccuredOn', 'CurrentDebtDaysSecondary',
       'DebtOccuredOnForSecondary', 
       'PlannedPrincipalPostDefault', 'PlannedInterestPostDefault', 'EAD1',
       'EAD2', 'PrincipalRecovery', 'InterestRecovery', 'RecoveryStage',
       'EL_V0', 'Rating_V0', 'EL_V1', 'Rating_V1', 'Rating_V2',
       'ActiveLateCategory', 'CreditScoreEsEquifaxRisk',
       'CreditScoreFiAsiakasTietoRiskGrade', 'CreditScoreEeMini',
       'PrincipalWriteOffs', 'InterestAndPenaltyWriteOffs',
       'PreviousEarlyRepaymentsBefoleLoan', 'GracePeriodStart',
       'GracePeriodEnd', 'NextPaymentDate', 'ReScheduledOn',
       'PrincipalDebtServicingCost', 'InterestAndPenaltyDebtServicingCost',
       'ActiveLateLastPaymentCategory']
      
dataset1=dataset.drop(miss,axis=1)

In [8]:
dataset1.shape

(134529, 77)

In [9]:
dataset1['NrOfScheduledPayments'].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: NrOfScheduledPayments, dtype: float64

In [10]:
#dataset.hist(bins=60, figsize=(20,10))
cols_del = ['ReportAsOfEOD', 'LoanId', 'LoanNumber', 'ListedOnUTC', 'DateOfBirth',
       'BiddingStartedOn','UserName','NextPaymentNr',
       'NrOfScheduledPayments','IncomeFromPrincipalEmployer', 'IncomeFromPension',
       'IncomeFromFamilyAllowance', 'IncomeFromSocialWelfare',
       'IncomeFromLeavePay', 'IncomeFromChildSupport', 'IncomeOther','LoanApplicationStartedDate','ApplicationSignedHour',
       'ApplicationSignedWeekday','ActiveScheduleFirstPaymentReached', 'PlannedInterestTillDate',
       'ExpectedLoss', 'LossGivenDefault', 'ExpectedReturn',
       'ProbabilityOfDefault', 'PrincipalOverdueBySchedule',
       'StageActiveSince', 'ModelVersion','WorseLateCategory']
dataset2 = dataset1.drop(cols_del,axis=1)
dataset2.shape

(134529, 48)

In [11]:
print(dataset2['Status'].value_counts())

Current    57135
Late       45772
Repaid     31622
Name: Status, dtype: int64

In [12]:
dataset2['Status'].head()

dataset2.query("Status!= 'Current'",inplace=True)

print(dataset2['Status'].value_counts())

Late      45772
Repaid    31622
Name: Status, dtype: int64

In [13]:
dataset2.columns

Index(['BidsPortfolioManager', 'BidsApi', 'BidsManual', 'NewCreditCustomer',
       'LoanDate', 'FirstPaymentDate', 'MaturityDate_Original',
       'MaturityDate_Last', 'VerificationType', 'LanguageCode', 'Age',
       'Gender', 'Country', 'AppliedAmount', 'Amount', 'Interest',
       'LoanDuration', 'MonthlyPayment', 'County', 'City', 'UseOfLoan',
       'Education', 'MaritalStatus', 'EmploymentStatus',
       'EmploymentDurationCurrentEmployer', 'OccupationArea',
       'HomeOwnershipType', 'IncomeTotal', 'ExistingLiabilities',
       'LiabilitiesTotal', 'RefinanceLiabilities', 'DebtToIncome', 'FreeCash',
       'MonthlyPaymentDay', 'LastPaymentOn', 'DefaultDate', 'Rating', 'Status',
       'Restructured', 'CreditScoreEsMicroL', 'PrincipalPaymentsMade',
       'InterestAndPenaltyPaymentsMade', 'PrincipalBalance',
       'InterestAndPenaltyBalance', 'NoOfPreviousLoansBeforeLoan',
       'AmountOfPreviousLoansBeforeLoan', 'PreviousRepaymentsBeforeLoan',
       'PreviousEarlyRepaymentsCountBeforeLoan'],
      dtype='object')

In [14]:
dataset2["DefaultDate"]
dataset2['DefaultDate']=dataset2['DefaultDate'].fillna(0)
dataset2["DefaultDate"]

myli=[0]


dataset2['target']=np.where(dataset2.DefaultDate.isin(myli),0,1)
dataset2.count()
dataset2['target']
dataset2.shape

(77394, 49)

In [15]:
dataset2["target"].value_counts()

1    42794
0    34600
Name: target, dtype: int64

In [16]:

dataset2.shape

(77394, 49)

In [17]:
result=dataset2.dtypes
print(result)

BidsPortfolioManager                        int64
BidsApi                                     int64
BidsManual                                float64
NewCreditCustomer                            bool
LoanDate                                   object
FirstPaymentDate                           object
MaturityDate_Original                      object
MaturityDate_Last                          object
VerificationType                          float64
LanguageCode                                int64
Age                                         int64
Gender                                    float64
Country                                    object
AppliedAmount                             float64
Amount                                    float64
Interest                                  float64
LoanDuration                                int64
MonthlyPayment                            float64
County                                     object
City                                       object
UseOfLoan                                   int64
Education                                 float64
MaritalStatus                             float64
EmploymentStatus                          float64
EmploymentDurationCurrentEmployer          object
OccupationArea                            float64
HomeOwnershipType                         float64
IncomeTotal                               float64
ExistingLiabilities                         int64
LiabilitiesTotal                          float64
RefinanceLiabilities                        int64
DebtToIncome                              float64
FreeCash                                  float64
MonthlyPaymentDay                           int64
LastPaymentOn                              object
DefaultDate                                object
Rating                                     object
Status                                     object
Restructured                                 bool
CreditScoreEsMicroL                        object
PrincipalPaymentsMade                     float64
InterestAndPenaltyPaymentsMade            float64
PrincipalBalance                          float64
InterestAndPenaltyBalance                 float64
NoOfPreviousLoansBeforeLoan                 int64
AmountOfPreviousLoansBeforeLoan           float64
PreviousRepaymentsBeforeLoan              float64
PreviousEarlyRepaymentsCountBeforeLoan      int64
target                                      int32
dtype: object

In [18]:
dataset2.select_dtypes(include=np.number).columns.tolist()
dataset2.select_dtypes(include=np.object).columns.tolist()

['LoanDate',
 'FirstPaymentDate',
 'MaturityDate_Original',
 'MaturityDate_Last',
 'Country',
 'County',
 'City',
 'EmploymentDurationCurrentEmployer',
 'LastPaymentOn',
 'DefaultDate',
 'Rating',
 'Status',
 'CreditScoreEsMicroL']

In [19]:
cols_dell=('LoanDate','FirstPaymentDate','MaturityDate_Original','MaturityDate_Last','LastPaymentOn','DefaultDate')
#dataset2 = dataset2.drop(cols_dell,axis=1)
#dataset2.shape
#already dropped so no need to run again

KeyError: "[('LoanDate', 'FirstPaymentDate', 'MaturityDate_Original', 'MaturityDate_Last', 'LastPaymentOn', 'DefaultDate')] not found in axis"

In [ ]:
def genderiser(x):
    if x==0:
        return 'female'
    return 'male'
dataset2['Gender']=dataset2['Gender'].apply(genderiser)

def very(x):
    if x==0.0:
        return 'Not Set'
    elif x==1.0:
        return 'Income unverified'
    elif x==2.0:
        return 'Income unverified cross-referenced by phone'
    elif x==3.0:
        return 'Income verified'
    else:
        return 'Income and expenses verified'
dataset2['VerificationType']=dataset2['VerificationType'].apply(very)

def lim(x):
    if x==1:
        return 'estonian'
    elif x==2:
        return 'English'
    elif x==3:
        return "Russian"
    elif x==4:
        return "Finnish"
    elif x==5:
        return "German"
    elif x==6:
        return "Spanish"
    elif x==9:
        return "Slovakian"
    else:
        return "Others"
 
dataset2['LanguageCode']=dataset2['LanguageCode'].apply(lim)

def edu(x):
    if x==-1:
        return 'Not Present'
    elif x==0:
        return 'Not Present'
    elif x==1:
        return 'Primary education'
    elif x==2:
        return 'Basic education'
    elif x==3:
        return 'Vocational education'
    elif x==4:
        return 'Secondary education'
    elif x==5:
        return 'Higher education'

    
dataset2['Education']=dataset2['Education'].apply(edu)

def loan(x):
    if x==-1:
        return 'Loan consolidation'
    if x==0:
        return 'Real estate'
    if x==1:
        return 'Home improvement'
    if x==2:
        return 'Business'
    if x==3:
        return 'Business'
    if x==4:
        return 'Education'
    if x==5:
        return 'Travel'
    if x==6:
        return 'Vehicle'
    if x==7:
        return 'Other'
    if x==8:
        return 'Health'
    if x==101:
        return 'Working capital financing'
    if x==102:
        return 'Purchase of machinery equipment '
    if x==104:
        return 'Accounts receivable financing'
    if x==106:
        return 'Acquisition of stocks'
    if x==107:
        return 'Acquisition of stocks'
    if x==108:
        return 'Acquisition of real estate'
    if x==110:
        return 'Other business All codes in format 1XX are for business loans that are not supported since October 2012'
    
dataset2['UseOfLoan']=dataset2['UseOfLoan'].apply(loan)        

#I will finish up on the rest of the category variables

In [20]:
dataset2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 77394 entries, 0 to 134528
Data columns (total 49 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   BidsPortfolioManager                    77394 non-null  int64
 1   BidsApi                                 77394 non-null  int64
 2   BidsManual                              77394 non-null  float64
 3   NewCreditCustomer                       77394 non-null  bool
 4   LoanDate                                77394 non-null  object
 5   FirstPaymentDate                        77394 non-null  object
 6   MaturityDate_Original                   77394 non-null  object
 7   MaturityDate_Last                       77394 non-null  object
 8   VerificationType                        77349 non-null  float64
 9   LanguageCode                            77394 non-null  int64
 10  Age                                     77394 non-null  int64
 11  Gender                                  77349 non-null  float64
 12  Country                                 77394 non-null  object
 13  AppliedAmount                           77394 non-null  float64
 14  Amount                                  77394 non-null  float64
 15  Interest                                77394 non-null  float64
 16  LoanDuration                            77394 non-null  int64
 17  MonthlyPayment                          70767 non-null  float64
 18  County                                  56879 non-null  object
 19  City                                    72350 non-null  object
 20  UseOfLoan                               77394 non-null  int64
 21  Education                               77349 non-null  float64
 22  MaritalStatus                           77349 non-null  float64
 23  EmploymentStatus                        77197 non-null  float64
 24  EmploymentDurationCurrentEmployer       76520 non-null  object
 25  OccupationArea                          77308 non-null  float64
 26  HomeOwnershipType                       75742 non-null  float64
 27  IncomeTotal                             77394 non-null  float64
 28  ExistingLiabilities                     77394 non-null  int64
 29  LiabilitiesTotal                        77394 non-null  float64
 30  RefinanceLiabilities                    77394 non-null  int64
 31  DebtToIncome                            77349 non-null  float64
 32  FreeCash                                77349 non-null  float64
 33  MonthlyPaymentDay                       77394 non-null  int64
 34  LastPaymentOn                           71782 non-null  object
 35  DefaultDate                             77394 non-null  object
 36  Rating                                  74666 non-null  object
 37  Status                                  77394 non-null  object
 38  Restructured                            77394 non-null  bool
 39  CreditScoreEsMicroL                     51208 non-null  object
 40  PrincipalPaymentsMade                   77394 non-null  float64
 41  InterestAndPenaltyPaymentsMade          77394 non-null  float64
 42  PrincipalBalance                        77394 non-null  float64
 43  InterestAndPenaltyBalance               77394 non-null  float64
 44  NoOfPreviousLoansBeforeLoan             77394 non-null  int64
 45  AmountOfPreviousLoansBeforeLoan         77394 non-null  float64
 46  PreviousRepaymentsBeforeLoan            58078 non-null  float64
 47  PreviousEarlyRepaymentsCountBeforeLoan  77394 non-null  int64
 48  target                                  77394 non-null  int32
dtypes: bool(2), float64(22), int32(1), int64(11), object(13)
memory usage: 28.2+ MB

In [22]:
dataset2.to_csv('Bondora_raw.csv',index=False)

In [ ]:
df=pd.read_csv('Bondora_raw.csv')

In [ ]:
df.head()